import Link from "next/link";
import { ShieldCheck, Globe, Zap, GitBranch, ArrowRight } from "lucide-react";
import { LandingNav } from "@/features/landing/sections/LandingNav";

const HIGHLIGHTS = [
  {
    icon: Globe,
    title: "24-rule AI crawlability audit",
    body: "We check robots.txt, sitemaps, schema coverage, redirect chains, missing llms.txt, broken links, and 18 more signals that determine whether AI engines can read and cite your site.",
  },
  {
    icon: ShieldCheck,
    title: "One-click fixes",
    body: "Critical issues like a missing llms.txt, blocked AI bots in robots.txt, or a missing sitemap get fixed with a single click — no developer needed.",
  },
  {
    icon: GitBranch,
    title: "Auto-deploy to GitHub and WordPress",
    body: "Connect your GitHub repo or WordPress site and Surven commits fixes directly. Your site updates automatically — no copy-paste, no waiting.",
  },
  {
    icon: Zap,
    title: "LLM-powered content rewrites",
    body: "Missing meta descriptions, alt text, schema, and FAQ schema are generated by AI using your actual page content — then committed straight to your site.",
  },
];

export const metadata = {
  title: "Crawlability Audit — Surven",
  description: "Find and fix every blocker stopping AI from reading and citing your site.",
};

export default function CrawlabilityFeaturePage() {
  return (
    <div className="min-h-screen bg-[var(--color-bg)]">
      <LandingNav />

      <main className="pt-16">
        {/* Hero */}
        <section className="max-w-4xl mx-auto px-6 pt-24 pb-16 text-center">
          <div
            className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-medium mb-6"
            style={{ backgroundColor: "rgba(150,162,131,0.15)", color: "var(--color-primary)" }}
          >
            <ShieldCheck className="h-3.5 w-3.5" />
            Crawlability Audit
          </div>
          <h1
            style={{
              fontFamily: "var(--font-display)",
              fontSize: "clamp(36px, 5vw, 62px)",
              fontWeight: 600,
              lineHeight: 1.1,
              letterSpacing: "-0.02em",
              color: "var(--color-fg)",
            }}
          >
            Fix what&apos;s blocking AI{" "}
            <span style={{ color: "var(--color-primary)" }}>from reading your site</span>
          </h1>
          <p className="mt-6 text-lg text-[var(--color-fg-muted)] leading-relaxed max-w-2xl mx-auto">
            AI engines can only cite pages they can crawl, parse, and trust. The Crawlability Audit finds every technical blocker across your entire site and shows you exactly how to fix it — or fixes it for you automatically.
          </p>
          <div className="mt-8 flex items-center justify-center gap-4">
            <Link
              href="/signup"
              className="inline-flex items-center gap-2 px-6 py-3 rounded-lg bg-[var(--color-primary)] text-white font-medium hover:bg-[var(--color-primary-hover)] transition-colors"
            >
              Audit your site free
              <ArrowRight className="h-4 w-4" />
            </Link>
            <Link
              href="/login"
              className="inline-flex items-center px-6 py-3 rounded-lg border border-[var(--color-border)] text-sm font-medium text-[var(--color-fg)] hover:border-[var(--color-primary)] transition-colors"
            >
              Sign in
            </Link>
          </div>
        </section>

        {/* Features grid */}
        <section className="max-w-5xl mx-auto px-6 pb-24">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
            {HIGHLIGHTS.map((h) => {
              const Icon = h.icon;
              return (
                <div
                  key={h.title}
                  className="rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)] p-6"
                >
                  <div
                    className="h-10 w-10 rounded-lg flex items-center justify-center mb-4"
                    style={{ backgroundColor: "rgba(150,162,131,0.15)" }}
                  >
                    <Icon className="h-5 w-5" style={{ color: "var(--color-primary)" }} />
                  </div>
                  <h3 className="font-semibold text-[var(--color-fg)] mb-2">{h.title}</h3>
                  <p className="text-sm text-[var(--color-fg-muted)] leading-relaxed">{h.body}</p>
                </div>
              );
            })}
          </div>
        </section>
      </main>
    </div>
  );
}
